### ISSUE TITLE
[CWM] Create API calls in FE

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap-monolith#4]
** Please track in Clockify CWM project **

## Description

Based on the API design for MykoMap discussed in https://github.com/DigitalCommons/mykomap/issues/267 and the [notes from the meeting on 20/8](https://docs.google.com/document/d/1aguAEMKfr8gqZRVkhJnb46VRJKd5wPMLLOQ1UmAKgFo/) and the API docs being created in #2 let's build the API requests into the FE.

## Acceptance Criteria

- FE is fetching data for main map call and marker data call from the BE. This data is currently mocked to my understanding.
- Do we need any translations at this stage?
- Do we need any unit tests?

**Comment by rogup** [comment]
I used https://github.com/hey-api/openapi-ts to quickly generate API calls from the openapi spec.

Then linked the UI up to these calls via the Redux Filter slice.

Since the full set of locations is now fetched async, I had to tweak the way this is initialised and stored too, but the architecture is roughly the same: there is a `features` variable in `geojson.ts` which holds a copy of the data that we don't change, which can be imported by other parts of the front-end app. I wanted to make this `features` object readonly using `Object.freeze()` but this didn't work with MapLibre, which doesn't want the geojson data to be readonly.

The changes are in `main`.

**Comment by rogup** [comment]
This is done for some mock data https://dev.maps.coop/cwm/?datasetId=test-500000
On this demo, a dataset of 500000 markers is loaded, and you can search for 'baz', which performs a filter.

The API calls were generated from the OpenAPI spec using @hey-api/openapi-ts, for speed of development, so we could get this working skeleton. But I'm keeping this ticket open since we are now going to migrate to using ts-rest.com

**Comment by rogup** [comment]
We have migrated to ts-rest so this can now be closed
