### ISSUE TITLE
[CWM] Website - Domain in Popup field confusion

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap-monolith#56]
**Describe the bug**
The domains are concatenated and listed as the main website. Seems to occur when a co-op only appears in the dotcoop data and has multiple domains and we have no way of easily identifying the primary website. 

**To Reproduce**

1. Open https://dev.maps.coop/cwm/?datasetId=north-america
2. Search for abarea in text seach
3. Select marker
4. 
![Image](https://github.com/user-attachments/assets/a22a4744-ad34-4884-97f5-d0daa3bf4c9a)

**Expected behavior**
In this case leave the Website section empty.

**App Version**
deploy-2024-11-05-100-g9554662

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox

**Smartphone (please complete the following information):**
 - NA

**Additional context**
Likely to be a data processing/merge issue and not an app bug. 
There is nothing to indicate if the first or last one is more likely to be the main one.

**Comment by lin-d-hop** [comment]
@rogup just confirmed the field is populated correctly from the 'website' variable on the FE

@wu-lee Nick can you check that the 'website' info is not populated from the 'domains' data?

**Comment by wu-lee** [comment]
Just to confirm here, this particular case, what happens is:
- We get the feed data from DotCoop in JSON, which has no website info, just a list of domains
- When normalising, the domains are copied into the "Website" field of the CSV as links, so that they appear in the old MM pop-ups
- Therefore the data we have for this entry, which is from the DC source only, has essentially the same in both fields, just bare domains in the Domain field, and URLs in the Website field.

**Comment by wu-lee** [comment]
Besides the above point, I think we decided this issue was now a non-issue? So moving to QA for closure.

**Comment by ColmDC** [comment]
Action is still require. Need extra step in later phase of data merging to clear out contents of the website field in the case that DotCoop is the only source of data for the co-op.

**Comment by wu-lee** [comment]
I think the latest data deployment resolves this?  I can't see the websites on the AbArea pop-up any more on dev-2.

**Comment by ColmDC** [comment]
Works for me on deploy-2024-11-19-36-gdf4a89a
