### ISSUE TITLE
[CWM] Dotcoop data not filtered correctly

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap-monolith#76]
**Describe the issue**
Filtering the DotCooperation data set only shows 33 co-ops registered with DotCoop

**Reproduce**
 - Run https://dev.maps.coop/cwm/?datasetId=delhi
 - In search panel, filter the DotCooperation data
 - Only 33 co-ops appear

**Expected behaviour**
 - There should be 4692

**Comment by ColmDC** [comment]
Could be related to 
https://github.com/DigitalCommons/mykomap-monolith/issues/49 and
https://github.com/DigitalCommons/mykomap/issues/275

**Comment by rogup** [comment]
There are only 33 entries with 'DC' in the searchable.json for delhi

https://github.com/DigitalCommons/demo-merge-map-data/blob/north-america-data/dc-ica-ncba-usda-ncg-ficu-fca.csv
has 2143 'DC registered' coops

Are you sure it's 4692 @ColmDC

**Comment by ColmDC** [comment]
>Are you sure it's 4692 @ColmDC 

Pretty sure. It's definitley thousands.

> In any case, there seems to be a problem with the dataset generation script [@wu-lee](https://github.com/wu-lee)

Yes, that was my hunch.

**Comment by ColmDC** [comment]
So https://github.com/DigitalCommons/mykomap/issues/275 needs fixing first and then revisit this one?

**Comment by wu-lee** [comment]
I think this will be fixed as soon as I regenerate the data and deploy it.  See https://github.com/DigitalCommons/mykomap/issues/275#issuecomment-2491804895

Although there are a few more DC organisations in the data: I count 4693. And there are 4770 items in the map data with DC in their Membership field. Si=o I think there must  be some duplicates... yes.  

|dcid|Name|Memberships|
|----|----|-----------|
|0W74Xq|Arizmendi Bakery Cooperative|NCBA;USFWC;DC|
|1KRrmK|wwwilliam.coop|CMC;DC|
|KEgjVW|Green Campus Coop|CMC;DC|
|NlD7DK|Cooperative ECTO|CMC;DC|
|NlDY5W|Cooperative etudiante de la Faculte de Droit de l'universite de Montreal|CMC;DC|
|PW9GmK|Space Age Federal Credit Union|DC|
|VKoB5q|U.S. Federation of Worker Cooperatives|NCBA;USFWC;DC|
|VKoYjW|NRTC|NCBA;DC|
|Wp2VXK|WEAVER WEBSITE DEVELOPMENT COOPERATIVE|CMC;DC|
|WvdaNK|Ferme entetee coop|CMC;DC|
|WwwNaW|La Coop Carbone|CMC;DC|
|YlB9jK|Federation cooperatives alimentation Quebec|CMC;DC|
|Zqn49l|CanTrust Hosting Co-operative|CMC;DC|
|kKmY5K|Co operative Housing Federation of Canada|CMC;DC|
|lDBzEq|EmPowerGHG Business Corp.|CMC;DC|
|nWdpJW|Confederation quebecoise des cooperatives d'habitation (CQCH)|CMC;DC|
|nqXrVl|FQCF|CMC;DC|
|oqrEmW|Central Ontario Co operative Housing Federation|CMC;DC|
|plVRjl|Fechimm|CMC;DC|
|plVogW|Sollio Cooperative Group|CMC;DC|
|qMxjbW|Federation des cooperatives funeraires du Quebec|CMC;DC|
|qeQOxq|The Drivers Cooperative|NCBA;USFWC;DC|
|qyzygK|Cooperative de developpement regional du Quebec|CMC;DC|
|rK3X5l|CCAP|CMC;DC|


One example is Arizmendi Bakery, which is in the DC data once,  but matches two rows of the USFWC due to Arizmendi Association of Cooperatives (http://arizmendi.coop/) sharing the domain of Arizmendi Bakery Panaderia and Pizzaria (http://valencia.arizmendi.coop). Essentially our assumption that one .coop domain == one organisation in all datasets is false.

**Comment by ColmDC** [comment]
Only remaining issue here comes from edge cases in the co-op deduplication, and not connected to map app functionality.

**Comment by ColmDC** [comment]
Closing, as edge case mention has new [ticket](https://github.com/DigitalCommons/mykomap-monolith/issues/76#issuecomment-2491848743).
